### PR TITLE
Use github action, remove travis, drop phpunit 4 support and support PHP 8.0

### PR DESCRIPTION
**Pull request by vasilvestre**
Ok so, I went too far :

"phpunit/phpunit" ^4.8 can't work anymore, all test are now 6.0+ compatible

FIx https://github.com/FriendsOfSymfony/oauth2-php/issues/127 and fix https://github.com/FriendsOfSymfony/oauth2-php/issues/123 and fix https://github.com/FriendsOfSymfony/oauth2-php/issues/126

Tests passes but I'm not sure it's still working, any help is welcome

### CODE REVIEW

**Comment by GuilhemN** [comment]
Wow that was fast! 
Thanks a lot, this is all good for me 👍

**Review by GuilhemN — APPROVED** [review]

**Comment by vasilvestre** [comment]
> Wow that was fast!
> Thanks a lot, this is all good for me 👍

Great ! Any release would be adopted through OSS PR I'm actually working on :)

**Comment by vasilvestre** [comment]
I've uncommented push action. Feel free to add a readme badge :)

**Comment by GuilhemN** [comment]
Thank you @vasilvestre!

**Comment by vasilvestre** [comment]
Any release date planned ?

**Comment by GuilhemN** [comment]
It's released https://github.com/FriendsOfSymfony/oauth2-php/releases/tag/1.3.1 😉

**Pull request merged**
