### PR TITLE
Use protected methods instead of private

### PR DESCRIPTION
**Pull request by borNfreee**
I need to extend `OAut2` class in my project but some methods are private.

### CODE REVIEW

**Comment by stof** [comment]
I'm -1 on this, especially without an explanation about what you want to achieve with these extension points. Anything protected needs to be taken into account for BC, so this makes a huge difference to private regarding maintenance

**Comment by borNfreee** [comment]
I'm need a small custom logic for [this method](https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2.php#L752) - so my CustomOAuth2 class just have one method. There is [a call of private method](https://github.com/FriendsOfSymfony/oauth2-php/blob/master/lib/OAuth2.php#L854) at the end of this method so I can't use it in my child class.

What would you suggest @stof ?
Thanks

**Comment by stof** [comment]
Well, what kind of custom logic, for which use case ? this is what we need, to figure out what the right extension point for that is rather than allowing to overwrite everything (and then having to maintain that).

**Comment by borNfreee** [comment]
Ok, this is an explanation of what I need to achieve:

I need to add some fields to the returned token when user make a request to `/oauth/v2/token?...`.
So I extended `TokenController` and override `tokenAction()`. This method calls `$this->server->grantAccessToken()` and here I need to modify result: I need to override this method (`grantAccessToken()`) to not return `Response` instance but return `$token` and then add my custom fields to that array. When new array is ready, I will create `Response` instance and will return it from my custom `TokenController`.

That's why I have to extend `OAuth2` class and override `grantAccessToken()` method that uses private method internally.

____

Another question (sorry if it is stupid) - what efforts you are talking about are needed after making this method `protected` instead of `private` and why it is a BC?

**Comment by stof** [comment]
returning a token instead of returning a Response is a very bad idea. you are changing the signature of the method, which means you break the rules of inheritance (the child class must respect the contract of the parent method

regarding the maintenance effort, we can do what we want with private code (change it, delete it) and we know it will never break projects using our code. but if we change protected stuff, we are changing extension points, and so we need to be very careful about BC implications (and extension points through inheritance are actually the worse one in regard to BC layers to implement. In Symfony, almost all cases where the BC layer was hard were related to inheritance being involved rather than composition)

**Comment by borNfreee** [comment]
Thanks for your detailed answer, it is very useful for understanding.
I just realized that I can achieve what I need by overriding public `createAccessToken()` method:

```php
class CustomOAuth2 extends OAuth
{
    public function createAccessToken(IOAuth2Client $client, $data, $scope = null, $access_token_lifetime = null, $issue_refresh_token = true, $refresh_token_lifetime = null)
    {
        $token = parent::createAccessToken(...);
        
        // add additional fields to the $token variable

        return $token;
    }
}
```

**Comment by stof** [comment]
and this is a good example of why we don't blindly accept such visibility change. It forces to look at cleaner implementation :smile:

**Pull request closed without merging**
